suppressMessages(library(gProfileR))
suppressMessages(library(RColorBrewer))
require(scales)
suppressMessages(library(monocle))
suppressMessages(library(Seurat))
suppressMessages(library(scater))
suppressMessages(library(xgboost))
suppressMessages(library(igraph))
suppressMessages(library(getopt))

source("R_src/getSigPerCells.R")
source("R_src/Enrichment.R")
source("R_src/castle.R")

spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'sourceRDS',  'i', 1, "character", "REQUIRED: 10X data to trained classifier prepared as Seurat object (.RDS generated by RodriguezAnalysis.R).",
  'targetRDS',  't', 1, "character", "REQUIRED: 10X data targeted prepared as seurat object (.RDS generated by SeuratCL.R (filtered, normalized)).",
  'targetMonocleRDS', 'm', 1, "character", "REQUIRED: 10X data targeted prepared as monocle object (.RDS generated by seuratMonocleOrdering.R).",
  'outdir',     'o',1, "character", 'Outdir path (default ./)'
), byrow=TRUE, ncol=5);

opt = getopt(spec)

if ( !is.null(opt$help) | is.null(opt$sourceRDS)) {
  cat("Perform perform cell type assignation using a source dataset and castle XGradientBoost tool")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}


source_seurat <- readRDS(opt$sourceRDS)
target_seurat <- readRDS(opt$targetRDS)



  seurat <- castleSeurat3(source_seurat,target_seurat,outdir = opt$outdir)
  
  if (!is.null(opt$targetMonocleRDS)) {
    target_monocle <- readRDS(opt$targetMonocleRDS)
    monocle <- transfertToMonocle(seurat,target_monocle,outdir = opt$outdir)
    saveRDS(monocle,paste(opt$outdir,"/monocleTrainedCt.rds",sep =""))
    
  }
  
  png(paste(opt$outdir,"/CellTypeLearnedPropGG.png",sep = ""))
  pie <- ggplot(seurat@meta.data,
                aes(x = factor(1), fill = factor(predicted))) + geom_bar(width = 1)
  pie <- pie + coord_polar(theta = "y") +
    theme(axis.title.x = element_blank(), axis.title.y = element_blank())
  print(pie)
  dev.off()
  
  png(paste(opt$outdir,"/CellTypeLearnedProp.png",sep = ""))
  pie(table(seurat@meta.data$predicted),labels = names(table(seurat@meta.data$predicted)),col = hue_pal()(4),main = paste("predicted prop"))
  dev.off()
  
  saveRDS(seurat,paste(opt$outdir,"/seuratTrainedCt.rds",sep = ""))

