##------------------------------------------------------------------------------
## L. Herault
##------------------------------------------------------------------------------

## -----------------------------------------------------------------------------
## Libraries
## -----------------------------------------------------------------------------

#Load required packages
suppressMessages(library(monocle))
suppressMessages(library(scran))
suppressMessages(library(getopt))



#load homemade function
source("R_src/data_preparation.R")



# Quality control and preparation of 10X data for analysis

## -----------------------------------------------------------------------------
## Command line args
## -----------------------------------------------------------------------------

spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'inputRDS',  'i', 1, "character", "REQUIRED: 10X data prepared as monocle object (.RDS generated by prepare_data.R).",
  "mitochFilter", "m",1, "numeric", "Ribosomal protein gene RNA proportion filtering (eg 0.1 to remove cells with more than 10% of Rbp transcripts",
  'outdir',     'o',1, "character", 'Outdir path (default ./)'
), byrow=TRUE, ncol=5);

opt = getopt(spec)

# if help was asked, print a friendly message
# and exit with a non-zero error code

args <- commandArgs()
if ( !is.null(opt$help) | is.null(opt$inputRDS)) {
  cat("Add cell cycle phases to each cells with scran, filter cells of low quality, control percentage mitochondrial transcripts")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}

if (is.null(opt$outdir)) {
  opt$outdir = "./"
}


gbm_cds <- readRDS(opt$inputRDS)


# print some stuff 
# head of the expression matrix
exprs(gbm_cds[c(1:5),c(1:5)])

# cells information 
head(pData(gbm_cds))

# gene information 
head(fData(gbm_cds))

# Estimating size factor and dispersion not needed anymore
#gbm_cds <- estimateSizeFactors(gbm_cds)
#gbm_cds <- estimateDispersions(gbm_cds)


# First getting cell cycle phases with cyclone function from package scrann (see data_preparation.R))
gbm_cds <- getCellCyclePhases(gbm_cds,outdir = paste(opt$outdir,"/cellCycle",sep =""))

# Filtering cells on UMI counts as explained in monocle doc 
# print num cells before filtering

print("Matrix dim before cell filtering :")
dim(pData(gbm_cds))

gbm_cds <- filterCells(gbm_cds,paste(opt$outdir,"/cellsFiltering",sep = ""),propMitochFilter = opt$mitochFilter)

# Filter on mitochondrial RNA proportion if specified
if (!is.null(opt$mitochFilter)) {
  valid_cells_Mito <- row.names(subset(pData(gbm_cds),
                                       percentMito < opt$mitochFilter))
  
  nonValidCellMito <- length(row.names(pData(gbm_cds)))-length(valid_cells_Mito)
  
  
}

# Filter cells with to few expressed genes to assign a cell cycle phases with cyclone
# not the the case with cellranger2 workflow

valid_cells <- row.names(subset(pData(gbm_cds),
            is.na(G2M_score) == FALSE &
            is.na(S_score) == FALSE &
            is.na(G1_score) == FALSE &
            is.na(phases) == FALSE ))

nonValidCellNum <- length(row.names(pData(gbm_cds)))-length(valid_cells)

print(paste(nonValidCellNum,"cells were filtered out because they express to few genes to assign a cell cycle phase with cyclone to them. "))

# Define final valid cells
if (!is.null(opt$mitochFilter)) {
  print(paste(nonValidCellMito,"cells were filtered out because more than", opt$mitochFilter, "of their transcripts are ribosomal protein gene RNA"))
  
  valid_cells <- valid_cells[valid_cells %in% valid_cells_Mito]
  }


#cells are row in pData(monocle) but column in monocle object
gbm_cds <- gbm_cds[,valid_cells]


#After

print("Matrix dim after cell filtering :")
dim(pData(gbm_cds))


saveRDS(object = gbm_cds,file = paste(opt$outdir,"/gbm_cds_treated.rds",sep =""))
