##------------------------------------------------------------------------------
## L. Herault
##------------------------------------------------------------------------------

## -----------------------------------------------------------------------------
## Libraries
## -----------------------------------------------------------------------------

suppressMessages(library(monocle))
suppressMessages(library(Seurat))
suppressMessages(library(BiocParallel))
suppressMessages(library(getopt))
suppressMessages(library(gridExtra))
suppressMessages(library(gProfileR))
suppressMessages(library(RColorBrewer))
suppressMessages(library(readxl))
suppressMessages(library(stringr))
suppressMessages(library(scales))
suppressMessages(library(cowplot))
suppressMessages(library(sctransform))
suppressMessages(library(stringr))
suppressMessages(library(plyr))


source("R_src/getSigPerCells.R")
source("R_src/Enrichment.R")
source("R_src/funForSeurat.R")


# Seurat 3 integration workflow

## -----------------------------------------------------------------------------
## Command line args
## -----------------------------------------------------------------------------

spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'inputFiles',  'i', 1, "character", "REQUIRED: 10X dataset paths prepared as hspc.combined object (.RDS generated by prepare_data.R) separated by +",
  'signaturesFile', 's',1, "character", "REQUIRED: signatures rds file",
  'outdir',     'o',1, "character", 'Outdir path (default ./)',
  "num_dim_CCA", 'q',1,"numeric", "First n dimensions of CCA to use for FindIntegrationAnchors Seurat function (15 by default)",
  "num_dim_weight", 'w',1,"numeric", "First n dimensions to use for IntegrateData Seurat function (15 by default)",
  "num_dim",      'n',1,"numeric", "First n dimensions of PCA to use for clustering, UMAP and TSNE (15 by default)",
  "num_dim_integrated",'N',1,"numeric", "Number of PCA dimension computed to analyse integrated data (40 by default)",
  "cores",        'c',1, "numeric", "Number of cores to use for ordering (for differencially expressed gene between clusters test)",
  "resolution",    'r',1, "numeric", "resolution for hspc.combined clustering",
  "correction",      "b",1,"character", "Covariable to use as blocking factor (eg one or several columns of pData: betch, cell cycle phases... separated by +)",
  "logfc_threshold", "l", 1, "numeric", "logfc threshold for finding cluster markers (1 cluster vs all deg) 0.25 by default",
  "rodriguezSig", "k", 1, "character", "path for xls file of Rodriguez result",
  "norm_method", "z",1, "character", "normalization method, logNorm (by default) or sctransform",
  "reusePca", "p", 0, "character","re use pca calculated before when caculating anchor weights for each dataset default to FALSE (permit to correct for cell cycle before integration)"
), byrow=TRUE, ncol=5);

opt = getopt(spec)

# if help was asked, print a friendly message
# and exit with a non-zero error code

args <- commandArgs()
if ( !is.null(opt$help) | is.null(opt$inputFiles)) {
  cat("Perform Seurat 3 integration workflow, then cluster the cell with seurat 3 at different resolutions")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}

print(opt$num_dim)
print(opt$num_dim_integrated)
print(opt$num_dim_CCA)
print(opt$num_dim_weigth)
#set default arguments values

if (is.null(opt$resolution)) {
  opt$resolution <- 0.6
}

if (is.null(opt$logfc_threshold)) {
  opt$logfc_threshold <- 0.25
}

if (is.null(opt$num_dim_CCA)) {
  opt$num_dim_CCA <- 15
}

if (is.null(opt$num_dim_weight)) {
  opt$num_dim_weight <- 15
}

if (is.null(opt$num_dim)) {
  opt$num_dim <- 15
}

if (is.null(opt$num_dim_integrated)) {
  opt$num_dim_integrated <- 40
}

if (is.null(opt$norm_method)) {
  opt$norm_method <- "logNorm"
}

if (is.null(opt$reusePca)) {
  opt$reusePca <- FALSE
}

