##------------------------------------------------------------------------------
## B . NDAO
##------------------------------------------------------------------------------

## SET DIRECTORY
setwd("/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/")

## -----------------------------------------------------------------------------
## Libraries
## -----------------------------------------------------------------------------

#Load required packages
suppressMessages(library(Seurat))
suppressMessages(library(scran))
suppressMessages(library(getopt))
suppressMessages(library(grid))
suppressMessages(library(gridExtra))
suppressMessages(library(scales))
suppressMessages(library(ggplot2))



#load homemade function
source("/shared/ifbstor1/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/R_src/data_preparation.R")



# Quality control and preparation of 10X data for analysis

## -----------------------------------------------------------------------------
## Command line args
## -----------------------------------------------------------------------------

spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'inputRDS',  'i', 1, "character", "REQUIRED: 10X data prepared as a list of seurat object and feature data table (.RDS generated by prepare_data.R).",
  "mitochFilter", "m",1, "numeric", "mitochondrial protein gene RNA percentage filtering (eg 10 to remove cells with more than 10% of mitoch protein transcripts, default none)",
  'outdir',     'o',1, "character", 'Outdir path (default ./)',
  'upperMad',    'u', 1, "numeric", "cells with more than u mads log counts will be discard (default 2)",
  "lowerMad",   'l', 1, "numeric", "cells with less than l mads log counts will be discard (default 2)"
), byrow=TRUE, ncol=5);

opt = getopt(spec)

# if help was asked, print a friendly message
# and exit with a non-zero error code

inputRDS <- "/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/input/10X_data_RNA_RA.rds"
outdir <- "/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/output/RNA/PLZF_RARA_RA/dataPreparation"

args <- commandArgs()
if ( !is.null(opt$help) | is.null(opt$inputRDS)) {
  cat("Add cell cycle phases to each cells with scran, filter cells of low quality, control percentage mitochondrial transcripts, ribosomal protein transcripts")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}

if (is.null(opt$outdir)) {
  opt$outdir = "./"
}

if (is.null(opt$mitochFilter)) {
  opt$mitochFilter <- 5
}

if (is.null(opt$upperMad)) {
  opt$upperMad <- 2
}

if (is.null(opt$lowerMad)) {
  opt$lowerMad <- 3
}


input <- readRDS(inputRDS)
seurat <- input$seurat
fd <- input$featureData
# print some stuff 

# Estimating size factor and dispersion not needed anymore
#gbm_cds <- estimateSizeFactors(gbm_cds)
#gbm_cds <- estimateDispersions(gbm_cds)


# First getting cell cycle phases with cyclone function from package scran (see data_preparation.R))
seurat <- getCellCyclePhasesSeurat(seurat,outdir = paste(outdir,"/cellCycle",sep =""))

# Change ensembl gene names in the seurat object ot gene short names to be able to use PercentageFeatureSet Seurat function for mt and rb transcript proportion
#check for dup genes

# Only needed if ensemble id (it is the case in the workflow)

dupGeneNames <- fd[which((duplicated(fd$gene_short_name))),"gene_short_name"]

if(length(dupGeneNames) == 0) {
  rownames(seurat) <- fData(gbm_to_seurat)$gene_short_name
  
} else {
  #write.csv(fd[which(is.element(fd$gene_short_name,dupGeneNames)),],
  #          paste(opt$outdir,"/dupGenesName.csv",sep = "")
  #)
  print("Dup gene short names existing, making them unique...")
  newSeuratCount <- as.matrix(GetAssayData(seurat,slot = 'counts',assay = "RNA"))
  rownames(newSeuratCount) <- make.unique(fd$gene_short_name, sep = "--")
  seurat <- CreateSeuratObject(counts = newSeuratCount,
                               assay = "RNA",
                               meta.data = seurat@meta.data
                               )

}

# Compute percent Rb and percent mt

seurat$percentMito <- PercentageFeatureSet(
  seurat,
  pattern = 'mt-',
  assay = 'RNA'
)


seurat$percentRibo <- PercentageFeatureSet(
  seurat,
  pattern = 'Rps|Rpl|Mrp', #it might be better to have the exact gene set through GO...
  assay = 'RNA'
)

# Filtering cells outside two MADs from median
# print num cells before filtering

print("Matrix dim before cell filtering :")
dim(seurat)

# plot qc metrics before filtering
png(paste(outdir,"/qcMetricsRaw.png",sep = ""))
VlnPlot(seurat, features = c("nFeature_RNA", "nCount_RNA", "percentMito","percentRibo"), ncol = 3,pt.size = 0.001)
dev.off()

# plot some correlation between qc metrics 
plot1 <- FeatureScatter(seurat, feature1 = "nCount_RNA", feature2 = "percentMito")
plot2 <- FeatureScatter(seurat, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")

png(paste(outdir,"/qcMetricsCr.png",sep = ""))
grid.arrange(plot1,plot2)
dev.off()

minCountThreshold <- exp(median(log(seurat@meta.data$nCount_RNA)) - opt$lowerMad*mad(log(seurat@meta.data$nCount_RNA)))
maxCountThreshold <- exp(median(log(seurat@meta.data$nCount_RNA)) + opt$upperMad*mad(log(seurat@meta.data$nCount_RNA)))

png(paste(outdir,"/cutOffLogCount.png",sep = ""))
VlnPlot(seurat, features = c( "nCount_RNA"),pt.size = 0.001) + 
  geom_hline(yintercept = minCountThreshold) +
  geom_hline(yintercept = maxCountThreshold)
dev.off()

seurat <- subset(seurat, subset = nCount_RNA > minCountThreshold &
                   nCount_RNA < maxCountThreshold & 
                   percentMito < opt$mitochFilter)

#Check if some cells don't have an assinged cell cycles phases 
table(!is.na(seurat@meta.data$phases))
png(paste(outdir,"/assignedPhases.png",sep = ""))
barplot(table(!is.na(seurat@meta.data$phases)),main="Phases assigned")
dev.off()

if("FALSE" %in% names(table(!is.na(seurat@meta.data$phases)))) {
  print("Discard cells with no cell cycle phases assinged (too few genes")
  print(table(!is.na(seurat@meta.data$phases))[1])
  seurat@meta.data$phases[is.na(seurat@meta.data$phases)] <- "noAssigned"
  Idents(seurat) <- "phases"
  seurat <- subset(seurat, idents = "noAssigned",invert = T)
  Idents(seurat) <- "orig.ident"
  
}

summary_phases <- ddply(seurat@meta.data,~phases, nrow)
colorPhases <- c(brewer.pal(9,"RdPu"))[c(3,6,9)]

bp_phasesClust_control <- ggplot(data.frame(summary_phases), aes(fill = phases, y = V1, x=phases)) +
  geom_bar(stat="identity")+
  scale_fill_manual( values= colorPhases)+
  ylab(label = "Cells")+xlab(label = "Phases") + theme_classic() +
  ggtitle("Traited")

ggsave(paste0(outdir, '/ccPhases_2', '.png'), plot = bp_phasesClust_control, device = 'png', path = NULL,
       scale = 1, width = 20, height = 20, units = 'cm', dpi = 300)
  

png(paste(outdir,"/ccPhases.png",sep = ""))
barplot(table(seurat@meta.data$phases),main="Phases") 
dev.off()

# plot qc metrics after filtering
png(paste(outdir,"/qcMetricsFiltered.png",sep = ""))
VlnPlot(seurat, features = c("nFeature_RNA", "nCount_RNA", "percentMito","percentRibo"), ncol = 3,pt.size = 0.001)
dev.off()

print("Matrix dim after cell filtering :")
print(dim(seurat))


saveRDS(object = seurat,file = paste(outdir,"/seurat_treated.rds",sep =""))
