##------------------------------------------------------------------------------
## L. Herault
##------------------------------------------------------------------------------

## -----------------------------------------------------------------------------
## Libraries
## -----------------------------------------------------------------------------

suppressMessages(library(monocle))
suppressMessages(library(Seurat))
suppressMessages(library(scran))
suppressMessages(library(getopt))



#load homemade function
source("R_src/data_preparation.R")

# R data preparation scripts for Rodiguez-Fraticelli data

## -----------------------------------------------------------------------------
## Command line args
## -----------------------------------------------------------------------------

spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'inputData',  'i', 1, "character", "REQUIRED: downloaded Rodriguez raw data (.RDS generated by prepare_data.R).",
  'outdir',     'o',1, "character", 'Outdir path (default ./)',
  'minPropCellExp', "p",1,"numeric", "Genes expressed in less than this proportion of cells are discarrded frome the analysis (0.001 by default)"
  ), byrow=TRUE, ncol=5);

opt = getopt(spec)

# if help was asked, print a friendly message
# and exit with a non-zero error code

args <- commandArgs()
if ( !is.null(opt$help) | is.null(opt$inputData)) {
  cat("Prepare Rodriguez - Fraticelli data as source for CaSTLe")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}

if (is.null(opt$outdir)) {
  opt$outdir = "./"
}

dir.create(opt$outdir,recursive = T,showWarnings = F)


if (is.null(opt$minPropCellExp)) {
  opt$minPropCellExp <- 0.001
  print(opt$minPropCellExp)
}

#setwd(opt$outdir)

#get Seurat3 Rodriguez
rawCountsPaths <-list.files(opt$inputData,full.names =T)

#make sure we gate the correct file (no MPP4)
rawCountsPaths <- rawCountsPaths[which(grepl(pattern = 'LTHSC|MPP2|MPP3|STHSC',rawCountsPaths))]


getSeuratRodriguez <- function(rawCountsPath) {
  
  rawTable <- read.csv(rawCountsPath)
  
  phenoData <- rawTable[,c(1:5)]
  rownames(phenoData) <- rawTable$cell_id
  data <- rawTable[,c(6:ncol(rawTable))]
  rownames(data) <- rawTable$cell_id
  seurat <- CreateSeuratObject(counts = t(data),meta.data = phenoData)
  
  #Use of Rodriguez QC to filter poor qualisty cells
  seurat <- subset(x = seurat, subset = pass_filter > 0.1)
  print(unique(seurat@meta.data$seq_run_id))
  return(seurat)
  
}

seuratObjects <- lapply(rawCountsPaths,getSeuratRodriguez)

# We do not take the MPP4
seuratAll <- merge(x = merge(x = seuratObjects[[1]], y = seuratObjects[[2]]),
                         y= merge(x = seuratObjects[[3]],y = seuratObjects[[4]]))

seuratAll@meta.data$library_id <- factor(seuratAll@meta.data$library_id,levels = c("LTHSC","STHSC", "MPP2", "MPP3"))


## Switch to Monocle object to more easily discard unexpressed genes

pd <- new("AnnotatedDataFrame", data = seuratAll@meta.data)
fd <- new("AnnotatedDataFrame", data = data.frame(gene_short_name = rownames(seuratAll)))
rownames(fd) <- fd$gene_short_name



monocleAll <- newCellDataSet(GetAssayData(object = seuratAll, slot = "counts"),
                             phenoData = pd,
                             featureData = fd,
                             lowerDetectionLimit = 0.1,
                             expressionFamily = negbinomial.size())



pData(monocleAll)$Total_mRNAs <- Matrix::colSums(exprs(monocleAll))
monocleAll <- detectGenes(monocleAll, min_expr = 0.1)

# Filter out genes expressed in too few cells
fData(monocleAll)$use_for_castle <- fData(monocleAll)$num_cells_expressed > opt$minPropCellExp * ncol(monocleAll)

gbm_to_seurat <- monocleAll[fData(monocleAll)$use_for_castle==T,]

seurat <- CreateSeuratObject(counts = exprs(gbm_to_seurat), meta.data = pData(gbm_to_seurat))

# Need normalized data for castle
seurat <- NormalizeData(object = seurat)


saveRDS(object = seurat,file = paste(opt$outdir,"/seuratForCastle.rds",sep =""))
