##------------------------------------------------------------------------------
## B . NDAO
##------------------------------------------------------------------------------

## SET DIRECTORY
#setwd("/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/")

## -----------------------------------------------------------------------------
## Libraries
## -----------------------------------------------------------------------------

suppressMessages(library(Seurat))
suppressMessages(library(BiocParallel))
suppressMessages(library(getopt))
suppressMessages(library(gridExtra))
#suppressMessages(library(gProfileR))
suppressMessages(library(RColorBrewer))
suppressMessages(library(readxl))
suppressMessages(library(stringr))
suppressMessages(library(scales))
suppressMessages(library(grid))
suppressMessages(library(ggplot2))




source("/shared/ifbstor1/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/R_src/getSigPerCells.R")
source("/shared/ifbstor1/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/R_src/Enrichment.R")
source("/shared/ifbstor1/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/R_src/funForSeurat.R")

# Seurat 3 analysis of an individual sample required for using CaSTLe script.

## -----------------------------------------------------------------------------
## Command line args
## -----------------------------------------------------------------------------

spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'inputRDS',  'i', 1, "character", "REQUIRED : 10X data prepared as monocle or seurat object (.RDS generated by prepare_data.R).",
  'outdir',     'o',1, "character", 'Outdir path (default ./)',
  "num_dim",      'n',1,"numeric", "Number of dimension to use for ordering (eg n first pc of PCA on input data) 10 by default",
  "correction",      "b",1,"character", "Covariable to use as blocking factor (eg one or several columns of pData: betch, cell cycle phases... separated by +)",
  "minPropCellExp", "p",1,"numeric", "minimal proportion of cells that expressed the genes kept for the analaysis 0.001 by default",
  "norm_method",    "z",1, "character", "normalisation method, logNorm seurat (by default) or sctransform",
  "resolution", "r", 1,"numeric", "resolution for Seurat clustering 0.9 by default",
  "signaturesFile", "s", 1, "character", "path to folder with signature list store as rds object",
  "identRemoved",    "d", 1, "character", "Optionnal cluster to remove only work if input is a seurat object",
  "nonExpressedGenesRemoved", "e", 0,"logical", "non expressed gene already removed default to FALSE",
  "gprofiler", "g", 0, "logical", "if true doing gprofiler default to true",
  "logfc_threshold", "l", 1, "numeric", "logfc threshold for finding cluster markers (1 cluster vs all deg) 0.25 by default"
  
), byrow=TRUE, ncol=5);

opt = getopt(spec)

## For testing
# 
# opt <- list()
outdir <- "/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/output/RNA/PLZF_RARA_CT/Seurat4"
correction <- "G2M_score+S_score+G1_score"
inputRDS <- "/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/output/RNA/PLZF_RARA_CT/dataPreparation/seurat_treated.rds"
#signatureFile <- "output/signatures/publicSignatures.rds"



# if help was asked, print a friendly message
# and exit with a non-zero error code

args <- commandArgs()
if ( !is.null(opt$help) | is.null(opt$inputRDS)) {
  cat("For an individual sample, perform PCA, tSNE, UMAP, Louvain clustering, diff expression between clusters with Seurat3 package with filtered poor quality cells data (gbm_cds monocle object)")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}


#set default arguments values

if (is.null(opt$num_dim)) {
  opt$num_dim <- 15
}

if (is.null(opt$resolution)) {
  opt$resolution <- 0.6
}

if (is.null(opt$minPropCellExp)) {
  opt$minPropCellExp <- 0.001
  print(opt$minPropCellExp)
}


if (is.null(opt$logfc_threshold)) {
  opt$logfc_threshold = 0.25
} 

print(paste("logfc threshold:", opt$logfc_threshold) )

if (is.null(opt$outdir)) {
  opt$outdir = "./"
}

if (is.null(opt$norm_method)) {
  opt$norm_method = "logNorm"
}



if (is.null(opt$nonExpressedGenesRemoved)) {
  opt$nonExpressedGenesRemoved = F
} else {
  opt$nonExpressedGenesRemoved = T
}

# if (is.null(opt$gprofiler)) {
#   opt$gprofiler <- T
# } else {
#   opt$gprofiler <- F
# }


# get correction vector
if (!is.null(correction)) {
  corrections <- strsplit(x = correction,split = "\\+")[[1]]
} else {
  corrections <- NULL
}



dir.create(outdir,recursive = T,showWarnings = F)

print(opt)

# Loading
seurat <- readRDS(inputRDS)

# Remove non expressed genes if not done
if(opt$nonExpressedGenesRemoved == F) {
  genesFiltered <- list(genes_before = dim(seurat)[1])
  
  print("remove non expressed genes (non expressed in at least X% of the cells X user option in monocle dp feature 5% in seurat tutorial 0,1%)")
  threshold <- opt$minPropCellExp * ncol(seurat)

  seurat <- CreateSeuratObject(counts = as.matrix(GetAssayData(seurat,slot = 'counts',assay = "RNA")),
                               assay = "RNA",
                               meta.data = seurat@meta.data,
                               min.cells = threshold)
  genesFiltered$genes_after <- dim(seurat)[1]
  
  png(paste(outdir,"/genesFiltering.png",sep = ""))
  barplot(unlist(genesFiltered),main = "Genes filtering")
  dev.off()
  
}



#################################################################################################
####################################### Seurat Workflow #########################################
#################################################################################################


classicSeuratWorkflow <- function(seurat, corrections,outdir) {
  dir.create(outdir,recursive = T,showWarnings = F)
  
  if (opt$norm_method == "sctransform") {
    
    seurat <- SCTransform(object = seurat, vars.to.regress = corrections)
    
  } else {
    
    seurat <- NormalizeData(object = seurat)
    seurat <- FindVariableFeatures(object = seurat,selection.method = "vst", nfeatures = 2000, verbose = T)
    seurat <- ScaleData(object = seurat,vars.to.regress = corrections)
    
  }
  
  seurat <- RunPCA(object = seurat)
  
  
  png(paste(outdir,"/ElbowPlot.png",sep =""))
  ElbowPlot(object = seurat,ndims = 30)
  dev.off()
  
  
  print("Clustering...")
  
  seurat <- FindNeighbors(object = seurat,dims = c(1:opt$num_dim),k.param = 20)
  seurat <- FindClusters(object = seurat,resolution = c(0.5,0.6,0.7,0.8,0.9,1,1.2))
  
  print("Running TSNE...")
  
  seurat <- RunTSNE(seurat,dims = c(1:opt$num_dim))
  
  print("Running UMAP...")
  
  seurat <- RunUMAP(seurat,dims = c(1:opt$num_dim))
  
  print("UMAP ok")
  print(colnames(seurat@meta.data))
  
  colPrefix <- "RNA_snn_res."
  if(opt$norm_method == "sctransform") {
    colPrefix <- "SCT_snn_res."
  }
  
  umapListRes <- list()
  tsneListRes <- list()
  for (r in c(0.6,0.8,1,1.2)) {
    umapListRes[[as.character(r)]] <- DimPlot(seurat,
                                              reduction = "umap",
                                              label = T,
                                              group.by = paste(colPrefix,r,sep="")) + 
      NoLegend() +
      ggplot2::ggtitle(paste("res",r))
    
    tsneListRes[[as.character(r)]] <- DimPlot(seurat,
                                              reduction = "tsne",
                                              label = T,
                                              group.by = paste(colPrefix,r,sep="")) + 
      NoLegend() +
      ggplot2::ggtitle(paste("res",r))
  }
  
  png(paste(outdir,"/tsne_different_res.png",sep = ""),height = 800,width = 800)
  grid.arrange(tsneListRes[[1]],tsneListRes[[2]],tsneListRes[[3]],tsneListRes[[4]])
  dev.off()
  
  png(paste(outdir,"/umap_different_res.png",sep = ""),height = 800,width = 800)
  grid.arrange(umapListRes[[1]],umapListRes[[2]],umapListRes[[3]],umapListRes[[4]])
  dev.off()
  
  
  
  
  Idents(seurat) <- paste(colPrefix,opt$resolution,sep = "")
  seurat@meta.data$numclust <- seurat@meta.data[,paste(colPrefix,opt$resolution,sep = "")]
  
  
  #Check for unwanted source of variation
  pPhases <- DimPlot(seurat,group.by = "phases")
  if (!is.null(seurat@meta.data$predicted)) {
    pPred <- DimPlot(seurat,group.by = "predicted")
  } else {
    pPred <- DimPlot(seurat)
  }
  
  pUMI <- FeaturePlot(seurat, "nCount_RNA")
  pMito <- FeaturePlot(seurat, "percentMito")
  
  png(paste(outdir,"/umap_factors.png",sep = ""),height = 800,width = 800)
  grid.arrange(pPhases,pPred,pUMI,pMito)
  dev.off()
  
  #Check for unwanted source of variation
  pPhases <- DimPlot(seurat,group.by = "phases",reduction = "tsne")
  if (!is.null(seurat@meta.data$predicted)) {
    pPred <- DimPlot(seurat,group.by = "predicted",reduction = "tsne")
  } else {
    pPred <- DimPlot(seurat,reduction = "tsne")
  }
  pUMI <- FeaturePlot(seurat, "nCount_RNA",reduction = "tsne")
  pMito <- FeaturePlot(seurat, "percentMito",reduction = "tsne")
  
  png(paste(outdir,"/tsne_factors.png",sep = ""),height = 800,width = 800)
  grid.arrange(pPhases,pPred,pUMI,pMito)
  dev.off()
  
  return(seurat)
  
}


## First without integration without correction
unintegrated <- seurat
DefaultAssay(unintegrated) <- "RNA"
classicSeuratWorkflow(unintegrated,correction = NULL,outdir = paste0(outdir,"/SeuratWoIntegrationWoCr/"))

## without integration with correction

classicSeuratWorkflow(unintegrated,correction = corrections,outdir = paste0(outdir,"/SeuratWoIntegrationWithCr/"))


## With integration without correction
if (!is.null(corrections)) {
  print("Seurat workflow without correction")
  classicSeuratWorkflow(seurat,correction = NULL,outdir = paste0(outdir,"/SeuratWithoutCr/"))
}

## With integration with correction

seurat <- classicSeuratWorkflow(seurat,corrections = corrections,outdir =outdir)

#################################################################################################
####################################### Markers analysis ########################################
#################################################################################################

markers <- FindAllMarkers(seurat,only.pos = T,logfc.threshold= opt$logfc_threshold)
markers <- markers[which(markers$p_val_adj < 0.05),]

write.table(x = markers,paste(outdir,"/markers.tsv", sep =""),sep = "\t",quote = F,row.names = F,col.names = T)


dir.create(paste(outdir,"/markers/",sep = ""))

ylab <- "LogNormalized UMI counts"
if (opt$norm_method == "sctransform") {
  ylab <- "Expression level"
}

for (numClust in unique(markers$cluster)) {
  print(head(markers[which(markers$cluster == numClust),],n=9))
  png(paste(outdir,"/markers/Cluster_",numClust,"_topGenesVlnPlot.png",sep =""),width = 1000, height = 1000)
  plot(VlnPlot(object = seurat, features = head(markers[which(markers$cluster == numClust),"gene"],n=9),pt.size = 0.5) + 
         labs(x = "Clusters",y= ylab,colour = "black") +
         theme(axis.text = element_text(size=20),
               plot.title = element_text(size=25)) )
  dev.off()
  
}



## Add signatures scores
dir.create(paste(outdir,"/cellSignatures/",sep = ""))
signatures <- readRDS(opt$signaturesFile)
names(signatures) <- paste0(names(signatures),"_",seurat$sampleName[1])

for (sig in c(1:length(signatures))) {
  sigName <- names(signatures)[sig]
  signature <- signatures[[sig]]
  seurat <- scoreCells3(seurat,signature,outdir= paste(outdir,"/cellSignatures/",sep=""),sigName)
}

#################################################################################################
##########                                Enrichment                                   ##########
#################################################################################################


# ## Enrichment
# 
# # Modify colnames of markers to use gProfileAnalysis function
# firstup <- function(x) {
#   substr(x, 1, 1) <- toupper(substr(x, 1, 1))
#   x
# }
# 
# colnames(markers) <- firstup(colnames(markers))
# 
# 
# #be careful background
# if(opt$gprofiler) {
# gprofiler_result <- gProfileAnalysis(deg_clust = markers,
#                                      outdir = paste(opt$outdir,"/gProfileR", sep =""),
#                                      background = rownames(seurat),
#                                      colors = hue_pal()(length(unique(markers$Cluster))))
# 
# saveRDS(gprofiler_result,file=paste(opt$outdir,"/gProfileR/gprofiler_results.rds",sep =""))
# }
# 
# 
# 
# # Test Rodriguez cluster sig
# if(!is.null(opt$rodriguezSig)) {
#   
#   clusterNames <- c("C1","C2","C3","Mk","Er","Ba","Neu","Mo1","Mo2", "preDC","preB","preT")
#   
#   RodriguezClustersSig <- lapply(X= c(1:length(clusterNames)),FUN = read_xlsx,path = opt$rodriguezSig)
#   
#   names(RodriguezClustersSig) <- clusterNames 
#   
#   getOnlyPos <- function(clustersSig) {
#     clusterSig <- clustersSig[which(clustersSig$log.effect > 0),]
#     return(clusterSig)
#   }
#   
#   RodriguezClustersSigPos <- lapply(X= RodriguezClustersSig, getOnlyPos)
#   
#   
#   signaturesRodriguez <- lapply(RodriguezClustersSigPos,"[[",1 )
#   
#   
#   firstup <- function(x) {
#     substr(x, 1, 1) <- toupper(substr(x, 1, 1))
#     x
#   }
#   
#   colnames(markers) <- firstup(colnames(markers))
#   
#   getClustEnrichForRodriguez <- function(clust,signatures,seurat,markers) {
#     clustSig <- lapply(signatures,testHyperSig3,seurat,markers,clust)
#     if (!is.null(seurat@meta.data$predicted)) {
#     propCellTypesLearned <- table(seurat@meta.data[which(seurat@meta.data$numclust==clust),"predicted"])/length(seurat@meta.data[which(seurat@meta.data$numclust==clust),"predicted"])
#     } else{
#       propCellTypesLearned <- NULL
#     }
#     clustInfo <- c(clustSig,propCellTypesLearned)
#     return(clustInfo)
#   }
#   
#   clust_list <- lapply(unique(markers$Cluster),getClustEnrichForRodriguez,signature=signaturesRodriguez,seurat =seurat,markers =markers) ##markers arg forgotten in testHyper sig
# 
#   names(clust_list) <- paste("cluster_",unique(markers$Cluster),sep="")
#   
#   clust_table <- as.data.frame(matrix(unlist(clust_list), nrow=length(unlist(clust_list[1]))))
#   colnames(clust_table) <- names(clust_list)
#   rownames(clust_table) <- names(clust_list[[1]])
#   
#   clust_df <- as.data.frame(t(clust_table))
#   
#   write.csv(clust_df,file = paste(opt$outdir,"/clustInfoRodriguez.csv",sep =""),quote = F)
#   
# }


#################################################################################################
##########                     Cluster summary table                                    #########
#################################################################################################

clust_table <- data.frame()

print("Creating cluster summary table ")

  firstup <- function(x) {
    substr(x, 1, 1) <- toupper(substr(x, 1, 1))
    x
  }

  colnames(markers) <- firstup(colnames(markers))

getClustInfo <- function(clust,signatures,seurat,markers) {
  
  clustInfo <- list()
  clustInfo$num_cells <- dim(seurat@meta.data[which(seurat@active.ident==clust),])[1]
  clustInfo$percent_cells <- clustInfo$num_cells/dim(seurat@meta.data)[1]
  percentPhases <- table(seurat@meta.data[which(seurat@active.ident==clust),"phases"])/length(seurat@meta.data[which(seurat@active.ident==clust),"phases"]) #In fact this is fraction not percentage
  
  if(!is.null(seurat@meta.data$predicted)) {
    percentPredicted <- table(seurat@meta.data[which(seurat@active.ident==clust),"predicted"])/length(seurat@meta.data[which(seurat@active.ident==clust),"predicted"]) #In fact this is fraction not percentage
    
    for (p in unique(seurat@meta.data$predicted)) {
      print(p)
      if (is.element(p,names(percentPhases))) {
        clustInfo[[p]] <- percentPhases[p] 
      } else {
        clustInfo[[p]] <- 0
      }
    }
    
  }
  
  for (p in c("G1_G0","S","G2_M")) {
    if (is.element(p,names(percentPhases))) {
      clustInfo[[p]] <- percentPhases[p] 
    } else {
      clustInfo[[p]] <- 0
    }
  }
  
  
  clustInfo$median_genes_expressed <- median(seurat@meta.data[which(seurat@active.ident==clust),"nFeature_RNA"])
  clustInfo$median_nUMI <- median(seurat@meta.data[which(seurat@active.ident==clust),"nCount_RNA"])
  clustInfo$median_percentMitochGenes <- median(seurat@meta.data[which(seurat@active.ident==clust),"percentMito"])
  
  
  clustSig <- lapply(signatures,testHyperSig3,seurat,markers,clust) 
  
  clustInfo <- c(clustInfo,clustSig)
  
}

#allSignatures <- c(signatures,signaturesRodriguez)

clust_list <- lapply(levels(unique(seurat@active.ident)),getClustInfo,signatures,seurat,markers)

names(clust_list) <- paste("cluster_",levels(unique(seurat@active.ident)),sep="")

saveRDS(clust_list,paste(opt$outdir,"/clust_list_save.rds",sep =""))

clust_table <- as.data.frame(matrix(unlist(clust_list), nrow=length(unlist(clust_list[1]))))
colnames(clust_table) <- names(clust_list)
rownames(clust_table) <- names(clust_list[[1]])


clust_df <- as.data.frame(t(clust_table))

write.table(x = clust_df,file = paste(outdir,"/clusters_table.tsv",sep =""),sep="\t",quote=F,col.names = NA)

saveRDS(seurat,file = paste(outdir,"/seurat.rds",sep = ""))



