##------------------------------------------------------------------------------
## L. Herault
##------------------------------------------------------------------------------

## -----------------------------------------------------------------------------
## Libraries
## -----------------------------------------------------------------------------

suppressMessages(library(monocle))
suppressMessages(library(Seurat))
suppressMessages(library(BiocParallel))
suppressMessages(library(getopt))
suppressMessages(library(gridExtra))
suppressMessages(library(gProfileR))
suppressMessages(library(RColorBrewer))
suppressMessages(library(readxl))
suppressMessages(library(stringr))
suppressMessages(library(scales))
suppressMessages(library(cowplot))
suppressMessages(library(sctransform))
suppressMessages(library(stringr))
suppressMessages(library(plyr))
suppressMessages(library(grid))


source("R_src/getSigPerCells.R")
source("R_src/Enrichment.R")
source("R_src/funForSeurat.R")


# Seurat 3 integration workflow

## -----------------------------------------------------------------------------
## Command line args
## -----------------------------------------------------------------------------

spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'inputFiles',  'i', 1, "character", "REQUIRED: 10X dataset paths prepared as hspc.combined object (.RDS generated by prepare_data.R) separated by +",
  'signaturesFile', 's',1, "character", "REQUIRED: signatures rds file",
  'outdir',     'o',1, "character", 'Outdir path (default ./)',
  "num_dim_CCA", 'q',1,"numeric", "First n dimensions of CCA to use for FindIntegrationAnchors Seurat function (15 by default)",
  "num_dim_weight", 'w',1,"numeric", "First n dimensions to use for IntegrateData Seurat function (15 by default)",
  "num_dim",      'n',1,"numeric", "First n dimensions of PCA to use for clustering, UMAP and TSNE (15 by default)",
  "num_dim_integrated",'N',1,"numeric", "Number of PCA dimension computed to analyse integrated data (40 by default)",
  "cores",        'c',1, "numeric", "Number of cores to use for ordering (for differencially expressed gene between clusters test)",
  "resolution",    'r',1, "numeric", "resolution for hspc.combined clustering",
  "correction",      "b",1,"character", "Covariable to use as blocking factor (eg one or several columns of pData: betch, cell cycle phases... separated by +)",
  "logfc_threshold", "l", 1, "numeric", "logfc threshold for finding cluster markers (1 cluster vs all deg) 0.25 by default",
  "rodriguezSig", "k", 1, "character", "path for xls file of Rodriguez result",
  "norm_method", "z",1, "character", "normalization method, logNorm (by default) or sctransform",
  "reusePca", "p", 0, "character","re use pca calculated before when caculating anchor weights for each dataset default to FALSE (permit to correct for cell cycle before integration)"
), byrow=TRUE, ncol=5);

opt = getopt(spec)

# if help was asked, print a friendly message
# and exit with a non-zero error code

args <- commandArgs()
if ( !is.null(opt$help) | is.null(opt$inputFiles)) {
  cat("Perform Seurat 3 integration workflow, then cluster the cell with seurat 3 at different resolutions")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}

#set default arguments values

if (is.null(opt$resolution)) {
  opt$resolution <- 0.6
}

if (is.null(opt$logfc_threshold)) {
  opt$logfc_threshold <- 0.25
}

if (is.null(opt$num_dim_CCA)) {
  opt$num_dim_CCA <- 15
}

if (is.null(opt$num_dim_weight)) {
  opt$num_dim_weight <- 15
}

if (is.null(opt$num_dim)) {
  opt$num_dim <- 15
}

if (is.null(opt$num_dim_integrated)) {
  opt$num_dim_integrated <- 40
}

if (is.null(opt$norm_method)) {
  opt$norm_method <- "logNorm"
}

if (is.null(opt$reusePca)) {
  opt$reusePca <- FALSE
}

blank <- grid.rect(gp=gpar(col="white"))

print(opt$reusePca)

dir.create(opt$outdir,recursive = T,showWarnings = F)


corrections <- strsplit(x = opt$correction,split = "\\+")[[1]]


dir.create(opt$outdir,recursive = T,showWarnings = F)


hspc.listFile <- strsplit(opt$inputFiles,split = "\\+")[[1]]

hspc.list <- list()
#load dataset 

for (i in 1:length(x = hspc.listFile)) {
  #For testing, in final workflow sampleName will be incorporated in metadata with the loading of cell ranger matrix
  sampleName <- strsplit(hspc.listFile[i],split = "/")[[1]][2]
  hspc.list[[i]] <- readRDS(hspc.listFile[i])
  hspc.list[[i]]@meta.data$sampleName <- sampleName
  hspc.list[[i]] <- RenameCells(hspc.list[[i]],add.cell.id = sampleName)
  
  if(opt$norm_method != "sctransform") {
    hspc.list[[i]] <- NormalizeData(object = hspc.list[[i]], verbose = FALSE)
    hspc.list[[i]] <- FindVariableFeatures(object = hspc.list[[i]], selection.method = "vst", 
                                           nfeatures = 2000, verbose = FALSE)
  } else {
    hspc.list[[i]] <- SCTransform(hspc.list[[i]],vars.to.regress = corrections,verbose = T)
  }
}


hspc.anchors <- FindIntegrationAnchors(object.list = hspc.list, dims = 1:opt$num_dim_CCA)

if(opt$reusePca) {
  print("Re use pca")
  hspc.combined <- IntegrateData(anchorset = hspc.anchors, weight.reduction = "pca", dims = 1:opt$num_dim_weight)
}

hspc.combined <- IntegrateData(anchorset = hspc.anchors, dims = 1:opt$num_dim_weight)

DefaultAssay(object = hspc.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
#Here certainly need to reuse SCTransform on combined data if norm_method = sct

hspc.combined <- ScaleData(object = hspc.combined, verbose = T,vars.to.regress = corrections)
hspc.combined <- RunPCA(object = hspc.combined, npcs = opt$num_dim_integrated, verbose = FALSE)


png(paste(opt$outdir,"/ElbowPlot.png",sep =""))
ElbowPlot(object = hspc.combined,ndims = opt$num_dim_integrated)
dev.off()


# t-SNE UMAP and Clustering
hspc.combined <- RunUMAP(object = hspc.combined, reduction = "pca", dims = 1:opt$num_dim)
hspc.combined <- RunTSNE(object = hspc.combined, reduction = "pca", dims = 1:opt$num_dim)
hspc.combined <- FindNeighbors(object = hspc.combined, reduction = "pca", dims = 1:opt$num_dim)
hspc.combined <- FindClusters(hspc.combined, resolution = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,1.2))

colPrefix <- "integrated_snn_res."

Idents(hspc.combined) <- paste(colPrefix,opt$resolution,sep = "")

hspc.combined@meta.data$AGE <- "Old"
hspc.combined@meta.data$AGE[which(hspc.combined@meta.data$age == "2_months")] <- "Young"



# Visualization of the samples
p1 <- DimPlot(object = hspc.combined, reduction = "umap", group.by = "sampleName")
p2 <- DimPlot(object = hspc.combined, reduction = "umap", label = TRUE)
p3 <- DimPlot(object = hspc.combined, reduction = "umap", group.by = "AGE")
p4 <- DimPlot(object = hspc.combined, reduction = "umap", group.by = "runDate")
p3tsne <- DimPlot(object = hspc.combined, reduction = "tsne", group.by = "AGE")
p4tsne <- DimPlot(object = hspc.combined, reduction = "tsne", group.by = "runDate")



png(paste(opt$outdir,"/umap_samples.png",sep =""),height = 800,width=1200)
grid.arrange(p1, p2,ncol = 2)
dev.off()

png(paste(opt$outdir,"/AGE.png",sep =""),height = 800,width=1200)
grid.arrange(p3, p3tsne,ncol = 2)
dev.off()

png(paste(opt$outdir,"/runDate.png",sep =""),height = 800,width=1200)
grid.arrange(p4, p4tsne,ncol = 2)
dev.off()

png(paste(opt$outdir,"/UmapClusters.png",sep =""),height = 800,width=1200)
DimPlot(object = hspc.combined, reduction = "umap", label = TRUE)
dev.off()


p1tsne <- DimPlot(object = hspc.combined, reduction = "tsne", group.by = "sampleName")
p2tsne <- DimPlot(object = hspc.combined, reduction = "tsne", label = TRUE)

png(paste(opt$outdir,"/tsne_samples.png",sep =""),height = 800,width=1000)
grid.arrange(p1tsne, p2tsne,ncol = 2)
dev.off()

#Visualistaoin one sample at a time
sampleNames <- unique(hspc.combined@meta.data$sampleName) 
dir.create(paste(opt$outdir,"/samples/umap/",sep = ""),recursive = T)
dir.create(paste(opt$outdir,"/samples/tsne/",sep = ""),recursive = T)

#samplePlotList <- list()
  for (s in sampleNames) {
    png(paste(opt$outdir,"/samples/umap/",s,".png",sep = ""))
    plot(DimPlot(object = hspc.combined, cells= grep(s, hspc.combined@meta.data$sampleName), reduction = "umap") + ggtitle(s))
    dev.off()
    png(paste(opt$outdir,"/samples/tsne/",s,".png",sep = ""))
    plot(DimPlot(object = hspc.combined, cells= grep(s, hspc.combined@meta.data$sampleName), reduction = "tsne") + ggtitle(s))
    dev.off()
  }


umapListRes <- list()
tsneListRes <- list()
for (r in c(0.6,0.8,1,1.2)) {
  umapListRes[[as.character(r)]] <- DimPlot(hspc.combined,
                                            reduction = "umap",
                                            label = T,
                                            group.by = paste(colPrefix,r,sep="")) + 
    NoLegend() +
    ggtitle(paste("res",r))
  
  tsneListRes[[as.character(r)]] <- DimPlot(hspc.combined,
                                            reduction = "tsne",
                                            label = T,
                                            group.by = paste(colPrefix,r,sep="")) + 
    NoLegend() +
    ggtitle(paste("res",r))
}

png(paste(opt$outdir,"/tsne_different_res.png",sep = ""),height = 800,width = 800)
grid.arrange(tsneListRes[[1]],tsneListRes[[2]],tsneListRes[[3]],tsneListRes[[4]])
dev.off()

png(paste(opt$outdir,"/umap_different_res.png",sep = ""),height = 800,width = 800)
grid.arrange(umapListRes[[1]],umapListRes[[2]],umapListRes[[3]],umapListRes[[4]])
dev.off()



hspc.combined@meta.data$numclust <- hspc.combined@meta.data[,paste(colPrefix,opt$resolution,sep = "")]


#Check for unwanted source of variation UMAP
pPhases <- DimPlot(hspc.combined,group.by = "phases")
if (!is.null(hspc.combined@meta.data$predicted)) {
  pPred <- DimPlot(hspc.combined,group.by = "predicted")
} else {
  pPred <- blank
}
pUMI <- FeaturePlot(hspc.combined, "Total_mRNAs")
pMito <- FeaturePlot(hspc.combined, "percentMito")

png(paste(opt$outdir,"/umap_factors.png",sep = ""),height = 800,width = 800)
grid.arrange(pPhases,pPred,pUMI,pMito)
dev.off()

#Check for unwanted source of variation tSNE
pPhases <- DimPlot(hspc.combined,group.by = "phases",reduction = "tsne")
if (!is.null(hspc.combined@meta.data$predicted)) {
  pPred <- DimPlot(hspc.combined,group.by = "predicted",reduction = "tsne")
} else {
  pPred <- blank
}
pUMI <- FeaturePlot(hspc.combined, "Total_mRNAs",reduction = "tsne")
pMito <- FeaturePlot(hspc.combined, "percentMito",reduction = "tsne")

png(paste(opt$outdir,"/tsne_factors.png",sep = ""),height = 800,width = 800)
grid.arrange(pPhases,pPred,pUMI,pMito)
dev.off()


#Check for genes

gene_list<- c("Pdzk1ip1","Mllt3",
              "Ctla2a","Cd27","Cd34",
              "Lig1","Hells","Tyms",
              "Notch2","Lst1",
              "Irf7","Stat1",
              "Pf4","Itga2b",
              "Klf1","Gata1",
              "Mpo","Cd48",
              "Fcer1a","Hdc",
              "Il7r","Thy1", # Ccr9 not found
              "Cdc20","Ccnb1","Racgap1",
              "Mzb1","Ly6d", "Trp53inp1",
              "Jun","Fos","Nr4a1","Jund")

gene_list <- gene_list[which(is.element(set=rownames(hspc.combined),el = gene_list))] 

dir.create(paste(opt$outdir,"/genes/umap/",sep =""),recursive = T)
dir.create(paste(opt$outdir,"/genes/tsne/",sep =""),recursive = T)
for (g in gene_list) {
  png(paste(opt$outdir,"/genes/umap/",g,".png",sep = ""))
  plot(FeaturePlot(hspc.combined,features = g))
  dev.off()
}

for (g in gene_list) {
  png(paste(opt$outdir,"/genes/tsne/",g,".png",sep = ""))
  plot(FeaturePlot(hspc.combined,features = g,reduction = "tsne"))
  dev.off()
}

#AGE prop for each cluster 
age_clust <- getAGEPropPerClustBarplot(hspc.combined)
#sample prop for each cluster
sample_clust <- getSamplePropPerClustBarplot(hspc.combined)
#runDate prop for each cluster
runDate_clust <- getRunDatePropPerClustBarplot(hspc.combined)

png(paste(opt$outdir,"/propPerClust.png",sep = ""))
grid.arrange(age_clust,sample_clust,runDate_clust,p2tsne)
dev.off()


## saving results

saveRDS(hspc.combined,paste(opt$outdir,"/combined.rds",sep =""))






