##------------------------------------------------------------------------------
## B . NDAO
##------------------------------------------------------------------------------


## Path to Rscript, for Rscript runing on cluster
#!/shared/ifbstor1/software/miniconda/envs/r-4.1.1/bin/Rscript


## SET DIRECTORY
#setwd("/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/")

## -----------------------------------------------------------------------------
## Libraries
## -----------------------------------------------------------------------------

#suppressMessages(library(monocle))
suppressMessages(library(Seurat))
suppressMessages(library(BiocParallel))
suppressMessages(library(getopt))
suppressMessages(library(gridExtra))
#suppressMessages(library(gProfileR))
suppressMessages(library(RColorBrewer))
suppressMessages(library(readxl))
suppressMessages(library(stringr))
suppressMessages(library(scales))
suppressMessages(library(cowplot))
suppressMessages(library(sctransform))
suppressMessages(library(stringr))
suppressMessages(library(plyr))
suppressMessages(library(grid))
suppressMessages(library(ggplot2))



source("/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/R_src/getSigPerCells.R")
source("/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/R_src/Enrichment.R")
source("/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/R_src/funForSeurat.R")


# Seurat 3 integration workflow

## -----------------------------------------------------------------------------
## Command line args
## -----------------------------------------------------------------------------

spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'inputFiles',  'i', 1, "character", "REQUIRED: 10X dataset paths prepared as seurat object (.RDS generated by prepare_data.R) separated by +",
  'signaturesFile', 's',1, "character", "REQUIRED: signatures rds file",
  'outdir',     'o',1, "character", 'Outdir path (default ./)',
  "num_dim_CCA", 'q',1,"numeric", "First n dimensions of CCA to use for FindIntegrationAnchors Seurat function (15 by default)",
  "num_dim_weight", 'w',1,"numeric", "First n dimensions to use for IntegrateData Seurat function (15 by default)",
  "num_dim",      'n',1,"numeric", "First n dimensions of PCA to use for clustering, UMAP and TSNE (15 by default)",
  "num_dim_integrated",'N',1,"numeric", "Number of PCA dimension computed to analyse integrated data (40 by default)",
  "cores",        'c',1, "numeric", "Number of cores to use for ordering (for differencially expressed gene between clusters test)",
  "resolution",    'r',1, "numeric", "resolution for smp.combined clustering",
  "correction",      "b",1,"character", "Covariable to use as blocking factor (eg one or several columns of pData: betch, cell cycle phases... separated by +)",
  "logfc_threshold", "l", 1, "numeric", "logfc threshold for finding cluster markers (1 cluster vs all deg) 0.25 by default",
  "rodriguezSig", "k", 1, "character", "path for xls file of Rodriguez result",
  "norm_method", "z",1, "character", "normalization method, logNorm (by default) or sctransform",
  "reusePca", "p", 0, "character","re use pca calculated before when caculating anchor weights for each dataset default to FALSE (permit to correct for cell cycle before integration)"
), byrow=TRUE, ncol=5);

opt = getopt(spec)

# if help was asked, print a friendly message
# and exit with a non-zero error code

inputFiles = "/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/output/RNA/PLZF_RARA_CT/Seurat4/seurat.rds+/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/output/RNA/PLZF_RARA_RA/Seurat4/seurat.rds"
outdir = "/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/output/RNA/Seurat4_integration"
correction <- "G2M_score+S_score+G1_score"


args <- commandArgs()
#if ( !is.null(opt$help) | is.null(opt$inputFiles)) {
  #cat("Perform Seurat 3 integration workflow, then cluster the cell with seurat 3 at different resolutions")
  #cat(getopt(spec, usage=TRUE))
  #q(status=1)
#}

#set default arguments values

if (is.null(opt$resolution)) {
  opt$resolution <- 0.5
}

if (is.null(opt$logfc_threshold)) {
  opt$logfc_threshold <- 0.25
}

if (is.null(opt$num_dim_CCA)) {
  opt$num_dim_CCA <- 15
}

if (is.null(opt$num_dim_weight)) {
  opt$num_dim_weight <- 15
}

if (is.null(opt$num_dim)) {
  opt$num_dim <- 15
}

if (is.null(opt$num_dim_integrated)) {
  opt$num_dim_integrated <- 50
}

if (is.null(opt$norm_method)) {
  opt$norm_method <- "logNorm"
}

if (is.null(opt$reusePca)) {
  opt$reusePca <- FALSE
}

print(opt$reusePca)

dir.create(outdir,recursive = T,showWarnings = F)


corrections <- strsplit(x = correction,split = "\\+")[[1]]


dir.create(outdir,recursive = T,showWarnings = F)


smp.listFile <- strsplit(inputFiles,split = "\\+")[[1]]

smp.list <- list()

#load dataset 
for (i in 1:length(x = smp.listFile)) {
  #For testing, in final workflow sampleName will be incorporated in metadata with the loading of cell ranger matrix
  smp.list[[i]] <- readRDS(smp.listFile[i])
  sampleName <- unique(smp.list[[i]]@meta.data$sampleName)
  smp.list[[i]] <- RenameCells(smp.list[[i]],add.cell.id = sampleName)
  
  if(opt$norm_method != "sctransform") {
    smp.list[[i]] <- NormalizeData(object = smp.list[[i]], verbose = FALSE)
    smp.list[[i]] <- FindVariableFeatures(object = smp.list[[i]], selection.method = "vst", 
                                           nfeatures = 2000, verbose = FALSE)
  } else {
    smp.list[[i]] <- SCTransform(smp.list[[i]],vars.to.regress = corrections,verbose = T)
  }
}


smp.anchors <- FindIntegrationAnchors(object.list = smp.list, dims = 1:opt$num_dim_CCA)

if(opt$reusePca) {
  print("Re use pca")
  smp.combined <- IntegrateData(anchorset = smp.anchors, weight.reduction = "pca", dims = 1:opt$num_dim_weight)
}

smp.combined <- IntegrateData(anchorset = smp.anchors, dims = 1:opt$num_dim_weight)


# Run the standard workflow for visualization and clustering
#Here certainly need to reuse SCTransform on combined data if norm_method = sct


classicSeuratWorkflow <- function(smp.combined, corrections,outdir) {
  dir.create(outdir,recursive = T)
  smp.combined <- ScaleData(object = smp.combined, verbose = T,vars.to.regress = corrections)
  smp.combined <- RunPCA(object = smp.combined, npcs = opt$num_dim_integrated, verbose = FALSE)
  
  
  png(paste(outdir,"/ElbowPlot.png",sep =""))
  ElbowPlot(object = smp.combined,ndims = opt$num_dim_integrated)
  dev.off()
  
  
  # t-SNE UMAP and Clustering
  smp.combined <- RunUMAP(object = smp.combined, reduction = "pca", dims = 1:opt$num_dim)
  smp.combined <- RunTSNE(object = smp.combined, reduction = "pca", dims = 1:opt$num_dim)
  smp.combined <- FindNeighbors(object = smp.combined, reduction = "pca", dims = 1:opt$num_dim)
  smp.combined <- FindClusters(smp.combined, resolution = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,1.2))
  
  colPrefix <- paste0(DefaultAssay(smp.combined),"_snn_res.")
  
  Idents(smp.combined) <- paste(colPrefix,opt$resolution,sep = "")
  
  smp.combined@meta.data$AGE <- "Old"
  smp.combined@meta.data$AGE[which(smp.combined@meta.data$age == "2_months")] <- "Young"
  
  
  
  # Visualization of the samples
  p1 <- DimPlot(object = smp.combined, reduction = "umap", group.by = "sampleName")
  p2 <- DimPlot(object = smp.combined, reduction = "umap", label = TRUE)
  p3 <- DimPlot(object = smp.combined, reduction = "umap", group.by = "AGE")
  p4 <- DimPlot(object = smp.combined, reduction = "umap", group.by = "runDate")
  p3tsne <- DimPlot(object = smp.combined, reduction = "tsne", group.by = "AGE")
  p4tsne <- DimPlot(object = smp.combined, reduction = "tsne", group.by = "runDate")
  
  
  
  png(paste(outdir,"/umap_samples.png",sep =""),height = 800,width=1200)
  grid.arrange(p1, p2,ncol = 2)
  dev.off()
  
  png(paste(outdir,"/AGE.png",sep =""),height = 800,width=1200)
  grid.arrange(p3, p3tsne,ncol = 2)
  dev.off()
  
  png(paste(outdir,"/runDate.png",sep =""),height = 800,width=1200)
  grid.arrange(p4, p4tsne,ncol = 2)
  dev.off()
  
  png(paste(outdir,"/UmapClusters.png",sep =""),height = 800,width=1200)
  DimPlot(object = smp.combined, reduction = "umap", label = TRUE)
  dev.off()
  
  
  p1tsne <- DimPlot(object = smp.combined, reduction = "tsne", group.by = "sampleName")
  p2tsne <- DimPlot(object = smp.combined, reduction = "tsne", label = TRUE)
  
  png(paste(outdir,"/tsne_samples.png",sep =""),height = 800,width=1000)
  grid.arrange(p1tsne, p2tsne,ncol = 2)
  dev.off()
  
  #Visualistaoin one sample at a time
  sampleNames <- unique(smp.combined@meta.data$sampleName) 
  dir.create(paste(outdir,"/samples/umap/",sep = ""),recursive = T)
  dir.create(paste(outdir,"/samples/tsne/",sep = ""),recursive = T)
  
  #samplePlotList <- list()
  for (s in sampleNames) {
    png(paste(outdir,"/samples/umap/",s,".png",sep = ""))
    plot(DimPlot(object = smp.combined, cells= grep(s, smp.combined@meta.data$sampleName), reduction = "umap") + ggtitle(s))
    dev.off()
    png(paste(outdir,"/samples/tsne/",s,".png",sep = ""))
    plot(DimPlot(object = smp.combined, cells= grep(s, smp.combined@meta.data$sampleName), reduction = "tsne") + ggtitle(s))
    dev.off()
  }
  
  
  umapListRes <- list()
  tsneListRes <- list()
  for (r in c(0.6,0.8,1,1.2)) {
    umapListRes[[as.character(r)]] <- DimPlot(smp.combined,
                                              reduction = "umap",
                                              label = T,
                                              group.by = paste(colPrefix,r,sep="")) + 
      NoLegend() +
      ggtitle(paste("res",r))
    
    tsneListRes[[as.character(r)]] <- DimPlot(smp.combined,
                                              reduction = "tsne",
                                              label = T,
                                              group.by = paste(colPrefix,r,sep="")) + 
      NoLegend() +
      ggtitle(paste("res",r))
  }
  
  png(paste(outdir,"/tsne_different_res.png",sep = ""),height = 800,width = 800)
  grid.arrange(tsneListRes[[1]],tsneListRes[[2]],tsneListRes[[3]],tsneListRes[[4]])
  dev.off()
  
  png(paste(outdir,"/umap_different_res.png",sep = ""),height = 800,width = 800)
  grid.arrange(umapListRes[[1]],umapListRes[[2]],umapListRes[[3]],umapListRes[[4]])
  dev.off()
  
  
  
  smp.combined@meta.data$numclust <- smp.combined@meta.data[,paste(colPrefix,opt$resolution,sep = "")]
  
  
  #Check for unwanted source of variation UMAP
  pPhases <- DimPlot(smp.combined,group.by = "phases")
  if (!is.null(smp.combined@meta.data$predicted)) {
    pPred <- DimPlot(smp.combined,group.by = "predicted")
  } else {
    pPred <-  DimPlot(smp.combined)
  }
  pUMI <- FeaturePlot(smp.combined, "nCount_RNA")
  pMito <- FeaturePlot(smp.combined, "percentMito")
  
  png(paste(outdir,"/umap_factors.png",sep = ""),height = 800,width = 800)
  grid.arrange(pPhases,pPred,pUMI,pMito)
  dev.off()
  
  #Check for unwanted source of variation tSNE
  pPhases <- DimPlot(smp.combined,group.by = "phases",reduction = "tsne")
  if (!is.null(smp.combined@meta.data$predicted)) {
    pPred <- DimPlot(smp.combined,group.by = "predicted",reduction = "tsne")
  } else {
    pPred <-  DimPlot(smp.combined,reduction = "tsne")
  }
  pUMI <- FeaturePlot(smp.combined, "nCount_RNA",reduction = "tsne")
  pMito <- FeaturePlot(smp.combined, "percentMito",reduction = "tsne")
  
  png(paste(outdir,"/tsne_factors.png",sep = ""),height = 800,width = 800)
  grid.arrange(pPhases,pPred,pUMI,pMito)
  dev.off()
  return(smp.combined)
}

print("Seurat workflow without integration")
DefaultAssay(object = smp.combined) <- "RNA"
smp.combined <- NormalizeData(object = smp.combined)
smp.combined <- FindVariableFeatures(object = smp.combined,selection.method = "vst", nfeatures = 2000, verbose = T)

if (!is.null(corrections)) {
  print("Seurat workflow without correction")
  classicSeuratWorkflow(smp.combined,correction = NULL,outdir = paste0(outdir,"/SeuratMergingWoIntegrationWoCr/"))
}

classicSeuratWorkflow(smp.combined,corrections = corrections,outdir = paste0(outdir,"/SeuratMergingWoIntegration/"))



print("Seurat workflow with integration")

DefaultAssay(object = smp.combined) <- "integrated"


if (!is.null(corrections)) {
  print("Seurat workflow without correction")
  classicSeuratWorkflow(smp.combined,correction = NULL,outdir = paste0(outdir,"/SeuratWithoutCr/"))
}

smp.combined <- classicSeuratWorkflow(smp.combined,corrections = corrections,outdir =outdir)



#AGE prop for each cluster 
age_clust <- getAGEPropPerClustBarplot(smp.combined)

#sample prop for each cluster
sample_clust <- getSamplePropPerClustBarplot(smp.combined)

#runDate prop for each cluster
runDate_clust <- getRunDatePropPerClustBarplot(smp.combined)

png(paste(outdir,"/propPerClust.png",sep = ""))
grid.arrange(age_clust,sample_clust,runDate_clust,
             DimPlot(object = smp.combined, reduction = "tsne", label = TRUE))
dev.off()


## saving results

saveRDS(smp.combined,paste(outdir,"/combined.rds",sep =""))






