##------------------------------------------------------------------------------
## B . NDAO
##------------------------------------------------------------------------------


## Path to Rscript, for Rscript runing on cluster
#!/shared/ifbstor1/software/miniconda/envs/r-4.1.1/bin/Rscript


## SET DIRECTORY
#setwd("/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/")

## -----------------------------------------------------------------------------
## Libraries
## -----------------------------------------------------------------------------

suppressMessages(library(Signac))
suppressMessages(library(Seurat))
suppressMessages(library(getopt))
suppressMessages(library(gridExtra))
suppressMessages(library(scales))
suppressMessages(library(grid))
suppressMessages(library(S4Vectors))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))

set.seed(2021)

source("/shared/ifbstor1/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/R_src/transferFuns.R")


spec = matrix(c(
  'help',        'h', 0, "logical",   "Help about the program",
  'inputOld',  'i', 1, "character", "REQUIRED: scRNA integrated dataset path prepared as seurat object (.RDS generated by seurat4_integration.R)",
  'inputNew', 'a',1, "character", "REQUIRED: new dataset path prepared as seurat object (.RDS generated by SignacSmpCL.R)",
  "num_dim_CCA", 'q',1,"numeric", "First n dimensions of CCA to use for FindTranferAnchors and TransferData Seurat functions (30 by default)",
  "num_dim_LSI", 'l',1,"numeric", "First n dimensions of LSI to use for the New query in TransferData Seurat functions (30 by default)",
  "discardFirstLsiDim", 'd',0,"logical", "discard first dim lsi for the query in TransferData function",
  "num_dim",      'n',1,"numeric", "First n dimensions of PCA to use for clustering, UMAP and TSNE (15 by default)",
  "num_dim_integrated",'N',1,"numeric", "Number of PCA dimension computed to analyse integrated data (40 by default)",
  "clustCol",    'r',1, "character", "cluster column name to transfer to new data",
  "outdir",      "o",1,"character", "outdir path"),
  
  byrow=TRUE, ncol=5);

opt = getopt(spec)

inputNew = "/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/output/RNA/Seurat4_integration/combined.rds"
inputOld = "/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/reference/seuratAUC_2.rds"
outdir = "/shared/projects/scrna_gmp_rara/stage_babacar/scranseq/analysis/output/RNA/Old_New_integration/"
clustCol <- "FinalCluster"

# if help was asked, print a friendly message
# and exit with a non-zero error code

args <- commandArgs()
if ( !is.null(opt$help)) {
  cat("Perform Seurat 4 integration workflow, then cluster the cell with seurat 4 at different resolutions")
  cat(getopt(spec, usage=TRUE))
  q(status=1)
}

#set default arguments values

if (is.null(opt$clustCol)) {
  #opt$clustCol <- "numclust"
  opt$clustCol <- "FinalCluster"
}

if (is.null(opt$num_dim_CCA)) {
  opt$num_dim_CCA <- 30
}

dimsCCA <- c(1:opt$num_dim_CCA)

if (is.null(opt$num_dim_LSI)) {
  opt$num_dim_LSI <- 30
}

if (is.null(opt$discardFirstLsiDim)) {
  dimsLSI <- c(1:opt$num_dim_LSI)
} else {
  dimsLSI <- c(2:opt$num_dim_LSI)
}

if (is.null(opt$num_dim_integrated)) {
  opt$num_dim_integrated <- 50
}

if (is.null(opt$num_dim)) {
  opt$num_dim <- 15
}


print(opt)

rna_old <- readRDS(inputOld)
rna_new0 <- readRDS(inputNew)

print("add metadata...")

rna_old$orig.type <- "RNA"
rna_new0$orig.type <- "RNA"
DefaultAssay(rna_new0) = "RNA"

print("set idents...")

Idents(rna_new0) <- clustCol
Idents(rna_old) <- clustCol

# transfer
#rna_old$numclust <- rna_old@meta.data[,clustCol]

transfer.anchors <- FindTransferAnchors(reference = rna_old, query = rna_new0)

## To improve discard first integratedLSI ?
celltype.predictions <- TransferData(anchorset = transfer.anchors, refdata = rna_old$FinalCluster)
rna_new <- AddMetaData(rna_new0, metadata = celltype.predictions)


# colors
colorTreatment <- c("#664CFF", "#FF8000")
colorCluster <- c("#E69F00", "#CC79A7", "#0072B2", "#009E73", "#D55E00", "#56B4E9")

# make rna_new$predicted.id as factor
rna_new$predicted.id <- factor(rna_new$predicted.id, levels = c("Rep", "Neu1", "Neu2", "Neu3", "NeuRA1", "NeuRA2"))
Idents(rna_new) = "predicted.id"

# add Treatment_clust as metadata
rna_new$Treatment_clust = paste(rna_new$predicted.id, rna_new$sampleName, sep = "_")
rna_new$Treatment_clust = factor(rna_new$Treatment_clust, levels = c("Rep_RNA_Ctrl", "Rep_RNA_RA", "Neu1_RNA_Ctrl", "Neu1_RNA_RA", "Neu2_RNA_Ctrl", "Neu2_RNA_RA", "Neu3_RNA_Ctrl", "Neu3_RNA_RA", "NeuRA1_RNA_Ctrl", "NeuRA1_RNA_RA", "NeuRA2_RNA_Ctrl", "NeuRA2_RNA_RA")) 

# % cell type annotations that match the full reference
table(rna_new$predicted.id %in% rna_old$FinalCluster)

# Nb cells per treatment, old vs new
table(rna_old$sampleName)
table(rna_new$sampleName)

# plot reference  and query labels 
p1 <- DimPlot(rna_old, group.by = "FinalCluster", label = TRUE, repel = TRUE, cols = colorCluster) + ggtitle("Old scRNA-seq cells") + 
  NoLegend()
p2 <- DimPlot(rna_new, group.by = "predicted.id", label = TRUE, repel = TRUE, cols = colorCluster) + ggtitle("New scRNA-seq cells") + 
  NoLegend() #+ scale_colour_hue(drop = FALSE)

png(paste(outdir,"/predictedNewvsOldclust.png", sep = ""),res = 300,height=6,width =10,units = "in") # 
grid.arrange(p1,p2,nrow = 1)
dev.off()



# Nb cells per cluster: Old vs New (fill)
nb_cells_old = summary(rna_old$FinalCluster)
nb_cells_new = summary(rna_new$predicted.id)
NbCellsPerClusterOldvsNew = data.frame(nb_cells_old, nb_cells_new)
NbCellsPerClusterOldvsNew$Cluster =  factor(rownames(NbCellsPerClusterOldvsNew), levels = c("Rep", "Neu1", "Neu2", "Neu3", "NeuRA1", "NeuRA2"))
rownames(NbCellsPerClusterOldvsNew) = NULL
colnames(NbCellsPerClusterOldvsNew) = c("Old", "New", "Cluster")


p1 = ggplot(data = NbCellsPerClusterOldvsNew , aes(x = Cluster, y = Old)) +
  geom_bar(stat = "identity", fill="#664CFF") +
  geom_text(aes(label=Old), vjust=1.6, color="white", size=3.5) +
  theme_classic() +
  ggtitle("Old") +
  ylab("Nb Cells") + xlab("")

p2 = ggplot(data = NbCellsPerClusterOldvsNew, aes(x = Cluster, y = New)) +
  geom_bar(stat = "identity", fill="#FF8000") +
  geom_text(aes(label= New), vjust=1.6, color="white", size=3.5) +
  theme_classic() +
  ggtitle("New") +
  ylab("") + xlab("Cluster") 
  

png(paste(outdir,"/CellsFreqPerCluster.png", sep = "") ,res = 300,height=6,width =10,units = "in") # 
grid.arrange(p1, p2, nrow = 2)
dev.off()

# Nb cells per cluster: Old vs New (dodge)
NbCells = c(rbind(NbCellsPerClusterOldvsNew$Old, NbCellsPerClusterOldvsNew$New))
clust_origine = rep(c("Old", "New"), 6)
Clust_name = c(rbind(c("Rep", "Neu1", "Neu2", "Neu3", "NeuRA1", "NeuRA2"), c("Rep", "Neu1", "Neu2", "Neu3", "NeuRA1", "NeuRA2")))

Old_New = tibble(Clust_name, clust_origine, NbCells)
Old_New$Clust_name = factor(Old_New$Clust_name, levels = c("Rep", "Neu1", "Neu2", "Neu3", "NeuRA1", "NeuRA2"))
Old_New$clust_origine = factor(Old_New$clust_origine, levels = c("Old", "New"))

p = ggplot(data = Old_New , aes(fill = clust_origine, x = Clust_name, y = NbCells)) +
  geom_bar( stat="identity", position = position_dodge2())+
  scale_fill_manual(values= c("#666600", "#660033"))+
  theme_classic() +
  ylab("Nb Cells") + xlab("")

png(paste(outdir,"/CellsFreqPerCluster_dodge.png", sep = "") ,res = 300,height=6,width =10,units = "in") # 
grid.arrange(p)
dev.off()


## Nb cells per cluster: CT: Old vs New  and RA: Old vs New (dodge)
clustersampleName <- ddply(rna_new@meta.data,~predicted.id + sampleName,nrow)

clustersampleName$sampleName = factor(clustersampleName$sampleName, levels = c("RNA_Ctrl", "RNA_RA"))

bp_treatmentClustNew = ggplot(data.frame(clustersampleName), aes(fill = sampleName,y = V1, x=predicted.id)) +
  #geom_bar( stat="identity", position="fill")+
  geom_bar( stat="identity", position = position_dodge2())+
  scale_fill_manual( values= colorTreatment)+
  ylab(label = "nCells")+xlab(label = "") +
  theme_classic() + coord_flip()


# Old clusters
clustersampleNameOld <- ddply(rna_old@meta.data,~FinalCluster + condition,nrow)

clustersampleNameOld$condition = factor(clustersampleNameOld$condition, levels = c("Control", "Treated"))

bp_treatmentClustOld = ggplot(data.frame(clustersampleNameOld), aes(fill = condition,y = V1, x=FinalCluster)) +
  #geom_bar( stat="identity", position="fill")+
  geom_bar( stat="identity", position = position_dodge2())+
  scale_fill_manual( values= colorTreatment)+
  ylab(label = "nCells")+xlab(label = "") +
  theme_classic() + coord_flip()


#Old and New Clusters together
treatment_legend <- get_legend(bp_treatmentClustNew)

bp_grid_OldNew <- plot_grid(bp_treatmentClustOld + theme(legend.position = "none", axis.line.y = element_blank(), 
                                                 axis.ticks.y = element_blank()) +ggtitle("Old"), 
                      bp_treatmentClustNew  + theme(legend.position = "none", axis.text.y = element_blank(), 
                                                  axis.title.y = element_blank(), axis.line.y = element_blank(), 
                                                  axis.ticks.y = element_blank()) + ggtitle("New"),
                      treatment_legend, rel_widths = c(2,2,0.5), nrow = 1)

ggsave(paste0(outdir, "BarPlot/",'BP_grid_OldNew_treatment_dodge', '.png'), plot = bp_grid_OldNew, device = 'png', 
       path = NULL, scale = 1, width = 15, height = 20, units = 'cm', dpi = 300)


# Shared cells between Old and New Clusters

shared_cells_per_cluster = function(seuratOld, seuratNew) {
  for (cl1 in levels(seuratNew@meta.data$predicted.id)) {
    
    for (cl2 in levels(seuratOld@meta.data$FinalCluster)) {
      
      shared_cl = table(seuratNew[,seuratNew@meta.data$predicted.id == cl1]$barcode %in% 
                          seuratOld[, seuratOld@meta.data$FinalCluster == cl2]$barcode)
      
      shared_cl = 100 * (shared_cl[2] / sum(shared_cl))

      cat(cl1,"-",cl2, ":", shared_cl, "\n")
    } 
  }
}

shared_cells_per_cluster(rna_old, rna_new)



shared_Rep = table(rna_new[, rna_new@meta.data$predicted.id == "Rep"]$barcode %in% 
        rna_old[, rna_old@meta.data$FinalCluster == "Rep"]$barcode)

shared_Rep = 100 * (shared_Rep[2]/sum(shared_Rep))

shared_Neu1 = table(rna_new[, rna_new@meta.data$predicted.id == "Neu1"]$barcode %in% 
        rna_old[, rna_old@meta.data$FinalCluster == "Neu1"]$barcode)

shared_Neu1 = 100 * (shared_Neu1[2]/sum(shared_Neu1))

shared_Neu2 = table(rna_new[, rna_new@meta.data$predicted.id == "Neu2"]$barcode %in% 
        rna_old[, rna_old@meta.data$FinalCluster == "Neu2"]$barcode)

shared_Neu2 = 100 * (shared_Neu2[2]/sum(shared_Neu2))

shared_Neu3 = table(rna_new[, rna_new@meta.data$predicted.id == "Neu3"]$barcode %in% 
        rna_old[, rna_old@meta.data$FinalCluster == "Neu3"]$barcode)

shared_Neu3 = 100 * (shared_Neu3[2]/sum(shared_Neu3))

shared_NeuRA1 = table(rna_new[, rna_new@meta.data$predicted.id == "NeuRA1"]$barcode %in% 
        rna_old[, rna_old@meta.data$FinalCluster == "NeuRA1"]$barcode)

shared_NeuRA1 = 100 * (shared_NeuRA1[2]/sum(shared_NeuRA1))

shared_NeuRA2 = table(rna_new[, rna_new@meta.data$predicted.id == "NeuRA2"]$barcode %in% 
        rna_old[, rna_old@meta.data$FinalCluster == "NeuRA2"]$barcode)

shared_NeuRA2 = 100 * (shared_NeuRA2[2]/sum(shared_NeuRA2))

shared_clust = shared_Rep + shared_Neu1 + shared_Neu2 + shared_Neu3 + shared_NeuRA1 + shared_NeuRA2
mean_shared_clust = shared_clust/6
cat("En moyenne,", mean_shared_clust,"% des cellules dans les nouveaux clusters proviennent des anciens qui leurs correspondent")



# PLZF-RARA-hcG expression per cluster

p1 = VlnPlot(rna_new, feature = "PLZF-RARA-hcG", pt.size = 0, group.by = "predicted.id", cols = colorCluster) #+ ggtitle("PLZF-RARA-hcG expression")
p2 = DotPlot(rna_new, feature = "PLZF-RARA-hcG", group.by = "predicted.id") #+ ggtitle("PLZF-RARA-hcG expression")

png(paste(outdir,"/PLZF-RARA-hcG_expression.png", sep = ""),res = 300,height=6,width =10,units = "in") # 
grid.arrange(p1,p2,nrow = 1)
dev.off()


# PLZF-RARA-hcG expression per cluster per treatment
p1 = VlnPlot(rna_new, feature = "PLZF-RARA-hcG", pt.size = 0, group.by = "Treatment_clust") + NoLegend()
png(paste(outdir,"/PLZF-RARA-hcG_expressionPerClusterPerTreatment.png", sep = ""),res = 300,height=6,width =10,units = "in") # 
grid.arrange(p1)
dev.off()


p = VlnPlot(rna_new, feature = "PLZF-RARA-hcG", pt.size = 0, group.by = "predicted.id", split.by = "sampleName", cols = rep(colorTreatment))
png(paste(outdir,"/PLZF-RARA-hcG_expressionPerClusterSplitPerSampleName.png", sep = ""),res = 300,height=6,width =10,units = "in") # 
grid.arrange(p)
dev.off()

# PLZF-RARA-hcG expression per cluster CT
rna_new_CT = rna_new[, rna_new$Treatment_clust %in% c("Rep_RNA_Ctrl", "Neu1_RNA_Ctrl", "Neu2_RNA_Ctrl", "Neu3_RNA_Ctrl")]
p = VlnPlot(rna_new_CT, feature = "PLZF-RARA-hcG", pt.size = 0, split.by = "sampleName", cols = rep(colorTreatment[1]))

png(paste(outdir,"/PLZF-RARA-hcG_expressionPerClusterCT.png", sep = ""),res = 300,height=6,width =10,units = "in") # 
grid.arrange(p)
dev.off()

# PLZF-RARA-hcG expression per cluster RA
rna_new_RA = rna_new[, rna_new$Treatment_clust %in% c("Rep_RNA_RA", "Neu1_RNA_RA", "Neu2_RNA_RA", "Neu3_RNA_RA", "NeuRA1_RNA_RA", "NeuRA2_RNA_RA")]
p = VlnPlot(rna_new_RA, feature = "PLZF-RARA-hcG", pt.size = 0, split.by = "sampleName", cols = rep(colorTreatment[2]))

png(paste(outdir,"/PLZF-RARA-hcG_expressionPerClusterRA.png", sep = ""),res = 300,height=6,width =10,units = "in") # 
grid.arrange(p)
dev.off()


## statitics associated with VlnPlots of PLZF-RARA-hcG

#PLZF-RARA-hcG expression per cluster  
Idents(rna_new) = "predicted.id"
PLZF_RARA_hcG_statsPerClust = FindAllMarkers(rna_new, features = "PLZF-RARA-hcG", logfc.threshold = 0.0)
write.table(PLZF_RARA_hcG_statsPerClust, file = paste0(outdir, "PLZF_RARA_hcG_statsPerClust.tsv"), sep = "\t", row.names = F, col.names = T, quote = F)


#PLZF-RARA-hcG expression per cluster per treatment 
Idents(rna_new) = "Treatment_clust"
PLZF_RARA_hcG_statsPerClustPerSample = FindAllMarkers(rna_new, features = "PLZF-RARA-hcG", logfc.threshold = 0.0)
write.table(PLZF_RARA_hcG_statsPerClustPerSample, file = paste0(outdir, "PLZF_RARA_hcG_statsPerClustPerSample.tsv"), sep = "\t", row.names = F, col.names = T, quote = F)

# PLZF-RARA-hcG expression per cluster on CT
Idents(rna_new_CT) = "Treatment_clust"
PLZF_RARA_hcG_CT_stats = FindAllMarkers(rna_new_CT, features = "PLZF-RARA-hcG", logfc.threshold = 0.0)
write.table(PLZF_RARA_hcG_CT_stats, file = paste0(outdir, "PLZF-RARA-hcG-CT_stats.tsv"), sep = "\t", row.names = F, col.names = T, quote = F)


#saveRDS(rna_new, paste0(opt$outdir, "/atac_integrated.rds"))
saveRDS(rna_new, paste0(outdir,"/rna_new.rds"))


shared_Rep = table(rna_new[, rna_new@meta.data$predicted.id == "Rep"]$barcode %in% 
                     rna_old[, rna_old@meta.data$FinalCluster == "Rep"]$barcode)

shared_Rep = 100 * (shared_Rep[2]/sum(shared_Rep))

Idents(rna_new) = "predicted.id"
for (cl1 in levels(rna_new@meta.data$predicted.id)) {
  for (cl2 in levels(rna_new@meta.data$predicted.id)) {
    DE = FindMarkers(rna_new, features = "PLZF-RARA-hcG", ident.1 = cl1, ident.2 = cl2, logfc.threshold = 0.1, verbose = FALSE)
    if (dim(DE)[1] == 0) {
      break }
    else if (cl1 != "NeuRA2" && cl1 !=  cl2) {
      cat(cl1,"  ", cl2); cat("\n")
      print(DE); cat("\n\n") }
  }
}

Idents(rna_new) = "Treatment_clust"

control = c("Rep_RNA_Ctrl", "Neu1_RNA_Ctrl", "Neu2_RNA_Ctrl", "Neu3_RNA_Ctrl", "NeuRA1_RNA_Ctrl", "NeuRA2_RNA_Ctrl")
control = factor(control, levels = c("Rep_RNA_Ctrl", "Neu1_RNA_Ctrl", "Neu2_RNA_Ctrl", "Neu3_RNA_Ctrl", "NeuRA1_RNA_Ctrl", "NeuRA2_RNA_Ctrl"))

treated = c("Rep_RNA_RA", "Neu1_RNA_RA", "Neu2_RNA_RA", "Neu3_RNA_RA", "NeuRA1_RNA_RA", "NeuRA2_RNA_RA")
treated = factor(treated, levels = c("Rep_RNA_RA", "Neu1_RNA_RA", "Neu2_RNA_RA", "Neu3_RNA_RA", "NeuRA1_RNA_RA", "NeuRA2_RNA_RA"))

for (cl1 in levels(control)) {
  for (cl2 in levels(treated)) {
    DE = FindMarkers(rna_new, features = "PLZF-RARA-hcG", ident.1 = cl1, ident.2 = cl2, logfc.threshold = 0.0, verbose = FALSE)
    if (dim(DE)[1] == 0) {
      break }
    else if (cl1 != "NeuRA2_RNA_Ctrl" && cl2 != "NeuRA2_RNA_RA" && cl1 !=  cl2 && DE$p_val < 0.05) {
      cat(cl1,"  ", cl2); cat("\n")
      print(DE); cat("\n\n") }
  }
}


Idents(rna_new) = "Treatment_clust"
for (cluster in levels(rna_new@meta.data$predicted.id)) {
  list_data[[cluster]] = FindMarkers(rna_new, features = "PLZF-RARA-hcG", ident.1 = paste(cluster, "RNA_Ctrl", sep = "_"), ident.2 = paste(cluster, "RNA_RA", sep = "_"), logfc.threshold = 0.0, min.pct = 0.0, verbose = FALSE)
  #list_data[[cluster]]$cluster = cluster
  #print(list_data[[cluster]]$cluster)
}

list_to_df = do.call("rbind", list_data)

write.table(x = list_to_df, file = paste0(outdir, "MarkersCtrlVsTreated_table.tsv"), quote = FALSE)
